# - src: 
#   name: 
#   version: 
- src: geerlingguy.java
  name: geerlingguy.java
 
- src: geerlingguy.jenkins
  name: geerlingguy.jenkins

- src: geerlingguy.docker
  name: geerlingguy.docker
- src: geerlingguy.kubernetes
  name: geerlingguy.kubernetes